### ISSUE TITLE
Support for complex object format

### ISSUE THREAD

**Issue by fvumbaca** [azohra/yaml.sh#1]
The parser will choke on complex objects like so:
```yaml
example: {name: feature, details: {type: request, priority: medium}}
```

The parser should handle this construct the same as:
```yaml
example:
  name: feature
  details:
    type: request
    priority: medium
```
