### ISSUE TITLE
Transpilation does not work with semi-complex YAML files

### ISSUE THREAD

**Issue by JJ** [azohra/yaml.sh#15]
**Describe the bug**

As soon as the yaml file is a bit complex, it breaks down using transpiled files with an "Unkown Ussage" message. The problem is that it includes both types of quotes, and there's no way to further quote it, it simply breaks. This file, for instance:

```yaml
---
entidad:
  - src/bankaccount/model.rs
  - src/bankcard/model.rs
  - src/bankfund/model.rs
  - src/controller/model.rs
  - src/paymentgroup/model.rs
  - src/savinggroup/model.rs
  - src/user/model.rs
  - src/utils/model.rs

test:
  - src/bankaccount/test_galvanic.rs
  - src/bankcard/test_galvanic.rs
  - src/bankfund/test.rs
  - src/controller/test.rs
  - src/paymentgroup/test.rs
  - src/savinggroup/test.rs
  - src/user/test_galvanic.rs
  - src/utils/test_galvanic.rs

lenguaje: rust 

fichero_tareas:
  - make.toml
```

Will create this transpiled file:

```text
entidad.[0]="src/bankaccount/model.rs"
entidad.[1]="src/bankcard/model.rs"
entidad.[2]="src/bankfund/model.rs"
entidad.[3]="src/controller/model.rs"
entidad.[4]="src/paymentgroup/model.rs"
entidad.[5]="src/savinggroup/model.rs"
entidad.[6]="src/user/model.rs"
entidad.[7]="src/utils/model.rs"
test.[0]="src/bankaccount/test_galvanic.rs"
test.[1]="src/bankcard/test_galvanic.rs"
test.[2]="src/bankfund/test.rs"
test.[3]="src/controller/test.rs"
test.[4]="src/paymentgroup/test.rs"
test.[5]="src/savinggroup/test.rs"
test.[6]="src/user/test_galvanic.rs"
test.[7]="src/utils/test_galvanic.rs"
lenguaje="rust"
fichero_tareas.[0]="make.toml"
```

Which, when expanded, will result in something like:

```bash
ysh -T 'entidad.[0]="src/bankaccount/model.rs"' 'entidad.[1]="src/bankcard/model.rs"' 'entidad.[2]="src/bankfund/model.rs"' 'entidad.[3]="src/controller/model.rs"' 'entidad.[4]="src/paymentgroup/model.rs"' 'entidad.[5]="src/savinggroup/model.rs"' 'entidad.[6]="src/user/model.rs"' 'entidad.[7]="src/utils/model.rs"' 'test.[0]="src/bankaccount/test_galvanic.rs"' 'test.[1]="src/bankcard/test_galvanic.rs"' 'test.[2]="src/bankfund/test.rs"' 'test.[3]="src/controller/test.rs"' 'test.[4]="src/paymentgroup/test.rs"' 'test.[5]="src/savinggroup/test.rs"' 'test.[6]="src/user/test_galvanic.rs"' 'test.[7]="src/utils/test_galvanic.rs"' 'lenguaje="rust' '"' 'fichero_tareas.[0]="make.toml"' -q lenguaje 
Unknown Ussage!
```

With the resulting error. I've tried to escape it usint the @Q quote, but it still does not work.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
