### ISSUE TITLE
Support for different list indentation styles

### ISSUE THREAD

**Issue by fvumbaca** [azohra/yaml.sh#5]
Proper yaml includes both of these list styles:
``` yaml
example_1:
  - item1
  - item2
example_2:
- item1
- item2
```

however yaml.sh only supports the `example_1` style. This sucks because many platforms (Kubernetes I am looking at you) prefer to, and provide examples of yaml that takes the form of `example_2`. If support for both styles can be achieved, this should be fixed
